# Generated by Django 6.0.6 on 2026-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("verdict", models.CharField(max_length=10)),
                ("confidence", models.IntegerField()),
                ("explanation", models.TextField()),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
